flickr/urls.py
from django.urls import path
from . import views

app_name='flickr'
urlpatterns =[
    path('', views.index, name='index'),
    path('search/<str:user_id>/', views.search, name='search')
]

flickr_api/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('flickr.urls'))
]

flickr/models.py
from django.db import models

# Create your models here.

flickr/forms.py
from django import forms

class UserIdForm(forms.Form):
    user_id = forms.CharField(required=True, min_length=10, max_length=100)

flickr/views.py
import os
from pathlib import Path
import environ
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import UserIdForm

import requests

# initial setup
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(BASE_DIR, '.env')

def index(request):
    """
    Renders the index page with the form.
    """

    if request.method == 'POST':
        user_id = request.POST['user_id']
        return redirect('flickr:search', user_id=user_id)
    form = UserIdForm()
    return render(request, 'flickr/index.html', {'form': form})

def search(request, user_id):
    method = '?method=flickr.photos.search'
    api_key = f'&api_key={env('KEY')}'
    pk = f'&user_id={user_id}'
    form = '&format=json&nojsoncallback=1'
    url = f'https://www.flickr.com/services/rest/{method}{api_key}{pk}{form}'

    response = []
    try:
        response = requests.get(url).json()
    except:
        return HttpResponse("Hello! You're seing me probably because 'SOMETHING WHENT WRONG'")
    
    photo_urls = []
    data = response['photos']['photo']
    for photo_data in data:
        photo_urls.append(f'https://live.staticflickr.com/{photo_data['server']}/{photo_data['id']}_{photo_data['secret']}_w.jpg')
    return render(request, 'flickr/results.html', {'photos': photo_urls})

flickr/templates/flickr/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav>
            <a href="{% url 'flickr:index' %}">Home</a> - <a href="#">Contact</a>
        </nav>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
    <footer>&copy;Flickr 2024</footer>
</body>
</html>

flickr/templates/flickr/index.html
{% extends 'flickr/base.html' %}

{% block title %}Enter Id{% endblock %}

{% block content %}
    <form method="post" action="{% url 'flickr:index' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">search</button>
    </form>
{% endblock %}

flickr/templates/flickr/results.html
{% extends 'flickr/base.html' %}

{% block title %}Results{% endblock %}
{% block content %}
    {% for photo in photos %}
      <img src="{{ photo }}" alt="photo thumbnail">
    {% empty %}
      No matched photos for the provided user id.
    {% endfor %}
{% endblock %}